'use strict';
(() => {
  const setup = 'https://docs.google.com/document/d/1npumTvaf2SRj2wdEUoBBuYLZXwqXxJNUvY3SNqrLfe0/edit';
  const notes = 'https://docs.google.com/document/d/1Lk82_-zfwNNajqDp2uIUlJI2VuKwxwW63QeafuF0Z1c/edit?tab=t.0';
  const repo = 'https://github.com/elsapassaro/ramendr-starter-kit';
  const sha = '840c7ae65068746e621bfb1e58fb419f6a9a2faa';
  const configs = {
    291: {title:'RHEL discovered application',status:'Closed',ns:'hammerdb',vm:'hammerdb-rhel9',drpc:'hammerdb-drpc',placement:'hammerdb-placement',db:'PostgreSQL 16',hdb:'4.12',managed:false,windows:false},
    292: {title:'RHEL GitOps-managed application',status:'In Progress',ns:'gitops-vms',vm:'hammerdb-rhel9',drpc:'dell-vm-drpc',placement:'dell-vm-placement',db:'PostgreSQL 16',hdb:'5.0',managed:true,windows:false},
    293: {title:'Windows discovered application',status:'Closed',ns:'hammerdb-win',vm:'hammerdb-win',drpc:'hammerdb-win-drpc',placement:'Verify referenced Placement',db:'SQL Server 2022 Express',hdb:'5.0',managed:false,windows:true},
    294: {title:'Windows GitOps-managed application',status:'New',ns:'Not yet specified',vm:'Not yet specified',drpc:'Not yet specified',placement:'Not yet specified',db:'SQL Server 2022 Express',hdb:'5.0',managed:true,windows:true}
  };
  const id = document.body.dataset.flow, c = configs[id];
  const esc = s => String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const jira = key => `<a href="https://redhat.atlassian.net/browse/${key}">${key}</a>`;
  const stage = (title,kind,owner,summary,items,gate) => ({title,kind,owner,summary,items,gate});
  const stages = [
    stage('Inventory and ownership','hub','Hub + both spokes','Identify the exact protected application, both disks and the active DR direction.',[
      `Record DRPC ${c.drpc}, its Placement reference, protected namespace ${c.ns}, VM ${c.vm}, both DataVolumes/PVCs and current source VMI.${c.windows&&c.managed?' First establish and record the unspecified Windows managed object names.':''}`,
      'Read owner references and selectors. Map PlacementDecision, VRG, VolumeReplication, ManifestWork, ManagedClusterView and ProtectedApplicationView where used. Record installed controller versions and readiness.',
      'Verify source is spoke-0 on edge95 and target is spoke-1 on edge97. preferredCluster expresses home, not proof of active placement.',
      'Discover current namespaces and console scopes. Hub CR views do not substitute for spoke-local VM, VRG or storage views.'
    ],'Complete the dependency/evidence map before initiation.'),
    stage(c.managed?'Prove GitOps handoff':'Prove object recovery', 'hub',c.managed?'ACM + ApplicationSet + Argo CD':'Ramen + OADP / Velero',c.managed?'A real generated Application must follow PlacementDecision.':'VM configuration and dependencies must be recoverable independently of disk replication.',c.managed?[
      'Verify both spokes are registered through GitOpsCluster argo-acm-clusters and the relevant registration Placement/ManagedClusterSetBinding. Inspect registration metadata only, never Secret contents.',
      'Verify ApplicationSet watch scope and RBAC for openshift-dr-ops, acm-placement generator fields and generated Applications. Record source revision, workload path, destination, ownership, sync/health and operation status.',
      'The recorded RHEL bootstrap is a fixed-destination Application in openshift-gitops plus a console type marker in openshift-dr-ops. Synced/Healthy and an ApplicationSet UI label do not prove managed recovery.',
      'Require an external credential-provisioning path on the target. RHEL needs namespace-local cloudinit-hammerdb; Windows has a separate initialization/credential mechanism.',
      c.windows?'VIRTDR-294 has no verified Windows managed manifest set in clusters/dell-s4. Define its workload, namespace and DR resources before testing; do not reuse the RHEL manifests as Windows definitions.':'Use the verified upstream clusters/dell-s4/hub-dr and workloads manifests. Record the tested commit. Resolve the shared runner spoke-0/spoke-1 name gap described in Setup Step 11 before repeatable bootstrap.'
    ]:[
      'Require DRPC Protected=True, source VRG KubeObjectsReady=True and ClusterDataProtected=True, OADP DataProtectionApplication readiness and an Available BackupStorageLocation.',
      'Verify terminal Velero backup success or a controlled S3 archive read-back containing the VM, both DataVolumes and required dependencies. An empty Backup CR list does not establish that the stored archive is missing.',
      c.windows?'The Windows VM uses EFI/Hyper-V configuration, not cloud-init. Preserve its actual VM configuration and namespace-local dependencies.':'Preserve the VM, both DataVolumes and cloudinit-hammerdb Secret. Verify virt-freezer freeze/unfreeze hooks and SELinux labeling of /mnt/ramendr-data.',
      'MinIO readiness and storage metadata validation alone do not prove that the workload object archive completed.'
    ],c.managed?'BLOCK if generated Applications, destination credentials or controller ownership are unverified.':'BLOCK if VM restore/archive evidence is unverified.'),
    stage('Establish active writes','guest','Source guest + OpenShift Virtualization','Record a timestamped database baseline while the source VM is running.',[
      c.windows?'Verify MSSQL$SQLEXPRESS is Running and RamenDR-HammerDB Scheduled Task is Running. Record TPC-C SUM(d_next_o_id) and UTC capture time.':'Verify ramendr-postgresql.service and ramendr-dr-hammerdb.service are active. Record TPC-C sum(d_next_o_id) and UTC capture time.',
      `Recorded HammerDB version: ${c.hdb}. The managed RHEL bootstrap left writers stopped; start them only as part of an authorized test and prove sustained count growth.`,
      'Record guest database timezone, history timestamp range and database identity. Save source-side continuity/audit evidence for later comparison.',
      'Failover is crash-consistent with active writes. A reachable source is not assumed stopped or fenced. A pre/post aggregate count is only a baseline, not a loss measurement.'
    ],'Source VMI, database and writer must be verified; preserve source-side evidence.'),
    stage('Validate every replica','storage','Ramen + Dell csi-addons + both arrays','Correlate root and database disk replication with the live RPO.',[
      'Verify active DRPolicy and selected VolumeReplicationClass schedule. dr-policy-15m / powerstore-vrc-15m are the recorded baseline, not an assumption for a new run.',
      'For each backing disk, record source/destination volume IDs, replication-session resource IDs, state OK, no error/degraded condition and last_sync_timestamp age within the active RPO.',
      'Require DRCluster/DRPolicy validation and source protection. Correlate VRG DataProtected=False/Replicating with per-PVC conditions, actual array syncs, ClusterDataProtected and DRPC Protected; do not infer an S3 failure from that condition alone.',
      'Check array UI active alerts with acknowledged and unacknowledged alerts included. Verify node/path health, worker NQN identity, assigned-array sessions and CSI readiness for the affected disks.',
      'Record lastGroupSyncTime and final available storage-sync evidence for subsequent RPO analysis.'
    ],'BLOCK if even one backing volume or required object-recovery dependency is unverified.'),
    stage('Capture UI baseline','hub','Hub Fleet management + Core platform','Verify read-only controls and capture the complete controller chain.',[
      'Data Services > Disaster recovery: inspect Overview, Topology, Policies and Protected applications. Capture active policy, source/target relationship, expanded DRPC Details and each DR Status popover.',
      'Check popover contrast, step labels, title/progression consistency and documentation links. Capture and file discrepancies immediately before proceeding.',
      'Capture ManagedCluster availability, placement decision, relevant orchestration CRs and operator/controller readiness in the correct scope.',
      c.managed?'Also capture GitOps operator, actual ArgoCD instance, GitOpsCluster, ApplicationSet conditions and generated Application resource tree/destination.':'GitOps evidence is N/A unless it actually owns a recovery-path resource; capture OADP/Velero recovery dependencies on the spokes.',
      'Capture both spokes VM/VMI, VRG, per-disk replication, PVC/PV handles and storage/array views. Start an evidence index with UTC, workload, state, cluster, scope, resource and file path.'
    ],'Finish baseline UI and cross-operator checks before selecting Failover.'),
    stage('Initiate through hub UI','hub','Authorized user + Data Services console','Capture enabled Failover, selected spoke-1 and the confirmation before submission.',[
      'Open the affected DRPC action menu and capture the enabled Failover option. A capability check does not authorize initiation.',
      'With explicit test authorization, open Failover, select spoke-1, inspect warnings and the latest available recovery timestamp, then capture and submit the confirmation.',
      'Do not trigger through oc patch, annotations or another CLI mutation. Repair browser access if needed.',
      'Immediately capture post-initiation DRPC and relevant controller states. Retain timestamped command evidence as a supplement, not a substitute for UI captures.'
    ],'Initiation is a state change and requires explicit authorization.'),
    stage('Promote target disks','storage','Hub Ramen + target VRG + Dell CSI','Follow the DRPC to VRG to VolumeReplication to PowerStore handoff.',[
      'Observe actual phase/progression and conditions rather than assuming every run emits identical intermediate labels. Capture each meaningful transition, warning and error.',
      'Require target VRG Primary, both target VolumeReplications Primary and both target PVCs Bound to the expected VSA-B destination handles.',
      'Check PV node topology, VolumeAttachments, launcher mount events, CSI controller/node readiness and NVMe namespace visibility. Two live paths alone do not establish usable volume access.',
      'Keep source resources intact until target-copy checks pass. An unmapped replica without a PV can be legitimate before promotion; missing PV is not proof of an orphan.',
      'Repeat blocking Data Services read-only verification at this state and capture storage/controller upstream-downstream evidence.'
    ],'Target promotion is the mandatory gate before any source cleanup.'),
    stage(c.managed?'Reconcile application placement':'Authorize source cleanup',c.managed?'hub':'guest',c.managed?'PlacementDecision + ApplicationSet + Argo CD':'Source spoke only, separately authorized',c.managed?'Prove automatic source removal and target deployment using promoted disks.':'FailedOver / Cleaning Up is intermediate; remove source objects only after the gate.',c.managed?[
      'Observe PlacementDecision selecting spoke-1 and a generated Application targeting that registered destination. Capture ApplicationSet conditions, deletion/creation handoff and Argo CD operation results.',
      'Verify the controller automatically cleans up source VM, DataVolume and PVC resources. Manual source deletion does not satisfy VIRTDR-'+id+' managed-app acceptance.',
      'Verify source workload termination and source VRG Secondary. Confirm no competing fixed-destination Application recreates the source workload.',
      'Verify target manifests bind promoted existing disks. Do not let CDI clone a new boot disk or provision a blank database disk over recovered state.',
      'If handoff stalls, stop and capture controller namespace-watch, registration, generator and ownership errors. Repair is a separate authorized action.'
    ]:[
      'Require separate explicit source-cleanup authorization after target promotion is proven. Failover authorization alone does not permit resource deletion.',
      'Confirm source cluster context before each action. Delete source VM gracefully and wait for its VMI to terminate.',
      'Delete source root/data DataVolumes before the PVCs they own. Do not manually delete PVs, array volumes, target resources or promoted VolumeReplications.',
      'Capture before/after each source VM, DataVolume and PVC deletion. Preserve timestamped command output and verify target disks remain intact.',
      'Force deletion or finalizer removal requires exact-object investigation and its own explicit authorization. Wait for source VRG Secondary and DRPC FailedOver/Completed.'
    ],c.managed?'Automatic reconciliation and recovered disk reuse must be evidenced.':'Do not confuse Cleaning Up with completion; destructive cleanup is separately authorized.'),
    stage('Boot and recover services','guest','Target OpenShift Virtualization + guest OS','Verify the recovered VMI and database auto-start on spoke-1.',[
      'Verify target VM/VMI Running, launcher ready, both recovered disks accessible, and final PlacementDecision on spoke-1.',
      c.windows?'Verify MSSQL$SQLEXPRESS and RamenDR-HammerDB. SQL Server may auto-start after a 1-2 minute delay; inspect service/event evidence before any authorized manual intervention.':'Verify ramendr-postgresql.service and ramendr-dr-hammerdb.service auto-started. Inspect bounded systemd status/journal if either fails.',
      c.windows?'Verify SQL Server crash recovery and that tpcc is queryable on the promoted data disk.':'Verify PostgreSQL WAL recovery and that tpcc is queryable from /mnt/ramendr-data/postgres/data.',
      'Confirm source workload is gone, source VRG Secondary, target VRG/VolumeReplications Primary and DRPC FailedOver/Completed. A running VM alone does not complete DR validation.'
    ],'Require both guest services and the completed protection/placement chain.'),
    stage('Measure RPO and continuity','guest','Recovered database + source/array evidence','Locate the exact write gap; distinguish recovered data from new target transactions.',[
      'Query history per minute around failover and establish the database timezone. Identify the last source-side row and first target-side row; calculate the gap duration.',
      'Count recovered rows between lastGroupSyncTime / verified last array sync and the last source row. Compare with source-side evidence to establish whether outstanding writes survived.',
      'Report configured RPO, actual sync age, last/first write timestamps, gap, recovered RPO-window count and the supported loss verdict.',
      'Recovered count growth mixes old data and new writes. If source-side evidence is insufficient, mark exact data loss unverified rather than asserting zero loss.',
      'Keep history intact. An optional quiesced test must stop writes before initiation and compare before target writer restart; it is a separately scoped alternative, not the active-write flow.'
    ],'A pre/post sum(d_next_o_id) comparison cannot replace history-gap analysis.')
  ];
  if(c.windows) stages.push(stage('Verify recovered desktop','guest','User RDP session','Confirm a booted Windows desktop without BSOD.',[
    'Ask the user to run ~/Repos/ugreener/scripts/rdp-hammerdb-win.sh spoke-1 for the recorded discovered workload. For the managed variant, verify or adapt the actual service/namespace access path before using that script.',
    'Wait for user confirmation of a healthy desktop. Shutdown Event Tracker is expected after crash-consistent recovery and can be dismissed.',
    'Record the RDP result. Do not substitute SSH service checks for desktop/BSOD verification.'
  ],'Windows acceptance remains incomplete until the user confirms desktop recovery.'));
  stages.push(stage('Stop writer and seal evidence','guest','Target guest + final cross-scope capture','Preserve a queryable database while preventing further load-driven disk growth.',[
    c.windows?'Stop-ScheduledTask -TaskName RamenDR-HammerDB; Disable-ScheduledTask -TaskName RamenDR-HammerDB. Keep MSSQL$SQLEXPRESS running.':'sudo systemctl disable --now ramendr-dr-hammerdb.service. Keep ramendr-postgresql.service running.',
    'Verify the writer is stopped/disabled and the transaction count is unchanged across two observations. Capture timestamped output.',
    'Repeat final Data Services tabs/popovers, DRPC, placement, application, protection/replication and controller readiness evidence. Record whether the active DRPolicy changed.',
    'Publish run results with before/after screenshot pairs, command evidence, RPO measurements, defects and unavailable views. Compare only applicable behavior with AWS/ODF; do not copy ODF thresholds, MirrorPeer/Submariner checks or cleanup scripts.',
    'End of this flow is recovery on spoke-1 with writers stopped. Relocate/failback is a separate test; after an authorized return, dashboard home placement becomes spoke-0 again.'
  ],'Completion needs placement, protection, guest, RPO and final evidence, not only a success banner.'));

  const rhelRead = `# Read-only examples. Context names are placeholders; map to real kubeconfigs.\noc --context=hub get drpc ${c.drpc} -n openshift-dr-ops -o yaml\noc --context=hub get drpolicy dr-policy-15m -o yaml\noc --context=hub get drcluster spoke-0 spoke-1 -o yaml\noc --context=source get vm,vmi,dv,pvc -n ${c.ns}\noc --context=source get vrg,volumereplication -n ${c.ns} -o yaml\noc --context=target get vrg,volumereplication -n ${c.ns} -o yaml\noc --context=target get vm,vmi,dv,pvc -n ${c.ns}\noc --context=target get events -n ${c.ns} --field-selector=reason=FailedMount`;
  const sql = c.windows?`-- Read-only SQL Server queries in the recovered tpcc database.\n-- Replace time placeholders after establishing database timezone.\nSELECT CONVERT(VARCHAR(16), h_date, 120) AS minute, COUNT(*) AS rows\nFROM history WHERE h_date BETWEEN '<start>' AND '<end>'\nGROUP BY CONVERT(VARCHAR(16), h_date, 120) ORDER BY 1;\nSELECT MAX(h_date) FROM history;\nSELECT COUNT(*) FROM history\nWHERE h_date BETWEEN '<last_sync>' AND '<last_source_write>';\nSELECT SUM(d_next_o_id) AS total_orders FROM district;`:`-- Read-only PostgreSQL queries in the recovered tpcc database.\n-- Replace time placeholders after establishing database timezone.\nSHOW timezone;\nSELECT date_trunc('minute', h_date) AS minute, count(*) AS rows\nFROM history WHERE h_date BETWEEN '<start>' AND '<end>'\nGROUP BY 1 ORDER BY 1;\nSELECT max(h_date) FROM history;\nSELECT count(*) FROM history\nWHERE h_date BETWEEN '<last_sync>' AND '<last_source_write>';\nSELECT sum(d_next_o_id) FROM district;`;
  const snippet = `# Partial verified upstream ApplicationSet excerpt, not live state\nmetadata:\n  name: dell-vm-workload\n  namespace: openshift-dr-ops\nspec:\n  generators:\n    - clusterDecisionResource:\n        configMapRef: acm-placement\n        labelSelector:\n          matchLabels:\n            cluster.open-cluster-management.io/placement: dell-vm-placement\n        requeueAfterSeconds: 180\n  template:\n    spec:\n      source:\n        repoURL: https://github.com/elsapassaro/ramendr-starter-kit.git\n        targetRevision: ocp-4.22-rhdr-dell\n        path: clusters/dell-s4/workloads\n      destination:\n        server: "{{server}}"\n        namespace: gitops-vms\n      syncPolicy:\n        automated:\n          prune: true\n          selfHeal: true`;
  const checklist = ['Ownership and scope mapped','Source guest writes and baseline captured',c.managed?'Generated Application follows PlacementDecision':'VM archive success or read-back verified','Every backing disk passes replication gate','All baseline UI controls and scopes verified','Failover target and confirmation captured','Target Primary / PVC handle gate passed',c.managed?'Automatic source cleanup proved':'Separate cleanup authorization and evidence retained','Source Secondary / target Primary verified','Guest auto-start and completed DRPC verified','History gap and RPO-window evidence retained',...(c.windows?['User confirms desktop boot without BSOD']:[]),'Writer stopped/disabled, database remains queryable','Final screenshots, defects and evidence index complete'];
  document.getElementById('app').innerHTML = `
    <nav><a href="../">Flow directory</a><a href="../../ramendr/">Environment</a>${Object.entries(configs).map(([n,v])=>`<a href="../virtdr-${n}/" ${n===id?'aria-current="page"':''}>${n}: ${v.title}</a>`).join('')}</nav>
    <h1>${jira('VIRTDR-'+id)} · ${c.title}</h1><p class="muted">End-to-end Dell PowerStore asynchronous failover · spoke-0 to spoke-1 · ${jira('VIRTDR-218')}</p>
    <div class="summary"><div class="panel"><span class="badge">Jira: ${c.status}</span><p>Status snapshot: 2026-10-01. ${c.managed?'Managed failover acceptance is still to be demonstrated.':'Jira records this discovered-flow task as closed; consult recorded evidence for the tested run.'}</p></div><div class="panel"><b>${c.db} + HammerDB ${c.hdb}</b><p>VM: ${c.vm}<br>Protected namespace: ${c.ns}<br>DRPC: ${c.drpc}</p></div><div class="panel"><b>${c.managed?'Controller-managed recovery':'Discovered workload recovery'}</b><p>${c.managed?'PlacementDecision / ApplicationSet / Argo CD; automatic source cleanup is required.':'OADP/Velero object restore; separate authorization is required for source cleanup.'}</p></div></div>
    <div class="notice"><b>Evidence boundaries:</b> this is a detailed procedure diagram, not a live observation or a completed run record. Recorded configuration, Jira scope and intended acceptance are distinguished below. Both original protected workloads have home/preferred placement on spoke-0. No failover or cluster mutation is executed by this page.</div>
    ${c.windows&&c.managed?'<div class="notice"><b>Windows managed readiness gap:</b> the verified upstream Dell folder contains RHEL VM manifests only. Namespace, DRPC, Placement, ApplicationSet, Windows manifest path and access Service for this scenario are not yet specified in the reviewed sources. These are explicit setup gates, not invented resource names.</div>':''}
    <h2>Topology and the three independent recovery paths</h2>
    <div class="sites"><div class="site hub"><h3>Control plane · hub / edge36</h3><p>ACM/MCE ManagedClusters, DRPC and Placement in openshift-dr-ops; Ramen hub controller; DF Multicluster Orchestrator provides Data Services UI. MinIO stores metadata and object backup data.</p><p>${c.managed?'GitOps: ArgoCD registration in openshift-gitops; ApplicationSet must actively consume PlacementDecision.':'Discovered: recover VM and dependencies through kube-object protection.'}</p></div><div class="site"><h3>Home site · spoke-0 / edge95</h3><p>Host-local subnet 192.168.130.0/24. Source VM and root/data disks. Ramen cluster controller, OpenShift Virtualization/CDI, OADP/Velero and PowerStore CSI/csi-addons.</p><p>VSA-A management 10.46.48.20<br>Storage 10.46.49.1 + 10.46.49.2, TCP/4420</p></div><div class="site storage"><h3>Recovery site · spoke-1 / edge97</h3><p>Host-local subnet 192.168.127.0/24. Target restores disk metadata, promotes replica volumes and starts recovered VM. Verify actual worker topology and volume attachment.</p><p>VSA-B management 10.46.48.30<br>Storage 10.46.49.4 + 10.46.49.3, TCP/4420</p></div></div>
    <div class="table-wrap"><table><thead><tr><th>Path</th><th>Producer and consumer</th><th>What must be proven</th></tr></thead><tbody><tr><td>Storage data</td><td>Guest writes / source PVC / Dell CSI / VSA-A async replication / VSA-B / target PVC</td><td>Both disks recovered from replica handles; actual sync age within live RPO; usable NVMe namespaces and mounts.</td></tr><tr><td>DR control</td><td>UI / hub DRPC / DRPolicy / ManifestWork and views where used / spoke VRG / per-volume replication</td><td>Desired and observed generations, roles, conditions, placement and completion agree.</td></tr><tr><td>Application configuration</td><td>${c.managed?'Git revision / PlacementDecision / ApplicationSet / generated Application / Argo CD / target VM':'VM objects / OADP Velero backup / MinIO S3 / target object restore / target VM'}</td><td>${c.managed?'Correct destination and ownership; automatic source cleanup; promoted disk reuse; target credentials provisioned.':'Archive contains required objects; restore preserves boot configuration and dependencies; cleanup is separately authorized.'}</td></tr><tr><td>Metadata network</td><td>Spokes / hub HTTPS route and ACM cluster proxy / MinIO bucket ramen-metadata</td><td>Private CA trusted through configured system trust; validation and archive evidence. Host-local clone subnets do not imply direct cross-site pod networking.</td></tr></tbody></table></div>
    <h2>Start-to-finish flow</h2><p class="muted">Read left to right. Each connector is sequential procedure order, not a measured duration. Click a stage for detailed handoffs, acceptance gates and evidence.</p>
    <div class="toolbar"><button id="out" aria-label="Zoom out">Zoom out</button><span id="zoom">100%</span><button id="in" aria-label="Zoom in">Zoom in</button><button id="fit">Fit flow</button><button id="reset">100%</button><span class="muted">Horizontal scroll at full scale. Fit gives an overview; use 100% to read.</span></div>
    <div class="wrap" id="wrap"><div class="sizer" id="sizer"><div id="dia"><svg id="svg" aria-hidden="true"></svg>${stages.map((s,i)=>`<article class="stage" data-kind="${s.kind}" style="left:${30+i*370}px;top:35px"><span class="num">STEP ${String(i+1).padStart(2,'0')}</span><h3>${s.title}</h3><p>${s.summary}</p><small>${s.owner}</small><a href="#step-${i+1}">Details and gate</a></article>`).join('')}</div></div></div>
    <h2>Detailed handoffs and blocking gates</h2><div class="details">${stages.map((s,i)=>`<section class="panel detail" id="step-${i+1}"><span class="owner">${s.owner}</span><h3>${String(i+1).padStart(2,'0')} · ${s.title}</h3><ul>${s.items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p class="gate">Gate: ${esc(s.gate)}</p></section>`).join('')}</div>
    <h2>Resource map and configuration evidence</h2><pre>${esc(c.managed&&!c.windows?`Hub\n  openshift-dr-ops/dell-vm-drpc\n    DRPolicy: dr-policy-15m\n    protectedNamespaces: [gitops-vms]\n    Placement: dell-vm-placement\n      PlacementDecision (controller-generated name)\n    ApplicationSet: dell-vm-workload\n      ConfigMap: acm-placement\n      generated Application: dell-vm-workload-{{name}}\n  openshift-gitops\n    GitOpsCluster: argo-acm-clusters\n    bootstrap Application: dell-vm-workload (fixed spoke-0, not proof of DR)\nSpokes / gitops-vms\n  VM: hammerdb-rhel9\n  DataVolume / PVC: hammerdb-rhel9-rootdisk (35Gi)\n  DataVolume / PVC: hammerdb-rhel9-datadisk (20Gi)\n  Secret dependency: cloudinit-hammerdb (values excluded)\n  Service: hammerdb-rhel9 (NodePort SSH)\n  VRG / per-PVC VolumeReplication (follow actual owner references)` : c.managed?`Windows managed resource map: pending setup verification\n  Hub DRPC / Placement / PlacementDecision / ApplicationSet: names TBD\n  Generated Argo CD Application / destination / namespace: TBD\n  Windows VM / DataVolumes / PVCs / credential provisioning / Service: TBD\n  RHEL reference model: openshift-dr-ops/dell-vm-drpc protects gitops-vms\n  Do not use the RHEL resource map as an observed Windows deployment.`:`Hub / openshift-dr-ops (current enrollment pattern)\n  DRPC: ${c.drpc}\n    DRPolicy: dr-policy-15m (verify active)\n    protectedNamespaces: [${c.ns}]\n    Placement: ${c.placement}\nSpokes / ${c.ns}\n  VM / VMI: ${c.vm}\n  root DataVolume / PVC: ${c.vm}-rootdisk\n  data DataVolume / PVC: ${c.vm}-datadisk\n  VRG / per-PVC VolumeReplication (follow actual owner references)\n  OADP / Velero object backup and restore\nHistorical logs may show namespace-local DRPCs; do not copy that enrollment pattern.`)}</pre>
    ${c.managed?`<p><a href="${repo}/blob/${sha}/clusters/dell-s4/hub-dr/applicationset.yaml">Verified RHEL ApplicationSet source</a> · <a href="${repo}/blob/${sha}/clusters/dell-s4/hub-dr/drpc.yaml">DRPC source</a> · <a href="${repo}/blob/${sha}/clusters/dell-s4/workloads/datavolumes.yaml">Initial disk provisioning source</a></p><pre>${esc(snippet)}</pre><p class="muted">Verified upstream commit ${sha}. This excerpt belongs to the RHEL managed reference. The initial blank data-disk and golden-image root provisioning must not replace recovered disks during failover. Repository content does not prove live Application source or an actively reconciled generator.</p>`:''}
    <h2>Read-only inspection and database examples</h2><div class="details"><section class="panel"><h3>Cluster-side inspection</h3><pre>${esc(c.windows&&c.managed?'# Placeholder contexts and object names; resolve before use.\noc --context=hub get applicationsets,applications -A\noc --context=hub get drpc -A\noc --context=hub get placementdecision -A\n# Inspect the selected Windows protected namespace on both spokes.':rhelRead)}</pre>${c.managed?`<pre>${esc('# Read-only, context is a placeholder; no Secret contents.\noc --context=hub get applicationset dell-vm-workload -n openshift-dr-ops -o yaml\noc --context=hub get applications -A -o yaml\noc --context=hub get gitopscluster -A\noc --context=hub get placementdecision -n openshift-dr-ops -l cluster.open-cluster-management.io/placement=dell-vm-placement -o yaml')}</pre>`:''}</section><section class="panel"><h3>RPO history-gap queries</h3><pre>${esc(sql)}</pre><p>Run SQL through the authenticated guest database client without exposing credentials. For SQL Server, use an input file to avoid nested shell quoting. Retain both source-side and recovered evidence.</p><p class="gate">Report: last source write, first target write, gap duration, sync timestamp/age, RPO-window count, continuity comparison and supported loss verdict.</p></section></div>
    <h2>Evidence capture map</h2><div class="table-wrap"><table><thead><tr><th>Surface</th><th>Baseline</th><th>Transitions / promotion gate</th><th>Completion</th></tr></thead><tbody>
    <tr><td>Hub Fleet / Data Services</td><td>All four tabs, policy, topology, expanded DRPC, status popover, enabled Failover</td><td>Target and confirmation; each meaningful phase/progression; repeat tabs, links, popovers and Details before next action</td><td>Expanded DRPC Completed, policy comparison, topology and placement</td></tr>
    <tr><td>Hub Fleet / application and clusters</td><td>ManagedClusters, PlacementDecision, application topology, relevant ManifestWork/views</td><td>Decision and delivery handoffs; source/target availability</td><td>Final selected cluster and resource ownership</td></tr>
    <tr><td>Hub Core / controllers and DR CRs</td><td>Actual installed operator versions/readiness, DRPC/DRPolicy/DRClusters, relevant orchestration objects</td><td>Changed conditions, observed generation, bounded events/logs and warnings</td><td>Controller readiness and consistent final conditions</td></tr>
    <tr><td>GitOps ${c.managed?'required':'normally N/A'}</td><td>${c.managed?'ArgoCD instance, GitOpsCluster, registration, ApplicationSet and generated Applications':'Inspect only if it actually owns a recovery dependency'}</td><td>${c.managed?'Destination switch, source cleanup and target sync/health; existing disk reuse':'No inferred GitOps handoff for discovered applications'}</td><td>${c.managed?'Target Application tree and no source ownership conflict':'Record applicability explicitly'}</td></tr>
    <tr><td>Spoke-local Core views</td><td>VRG, per-disk replication, VM/VMI, DV/PVC/PV, attachments, CSI/CDI and OADP</td><td>Target Primary and handles; before/after authorized mutations; source Secondary</td><td>Target Running / bound disks, controller health and protection/replication</td></tr>
    <tr><td>PowerStore UI + supplementary API</td><td>Both arrays, active alerts including both acknowledgment states, mappings, sessions and syncs</td><td>Per-volume promotion and usable worker namespace evidence</td><td>Actual replica handles, sessions, path state and array health</td></tr>
    <tr><td>Timestamped terminal / database evidence</td><td>Services, source VMI and TPC-C baseline</td><td>Commands paired to console captures; source stop and final sync timestamps</td><td>Guest auto-start, history gap, RPO result, writer stopped; Windows RDP confirmation</td></tr>
    </tbody></table></div><p class="muted">Use one session screenshot directory, 1920x1080 captures and ordered filenames identifying step, cluster, scope, resource and tab. Capture immediately before/after every authorized mutation; unchanged version pages need baseline/completion coverage. Mark inaccessible views unverified. Do not capture credentials or registration Secret contents.</p>
    <h2>Known history and diagnostic boundaries</h2><div class="panel"><p>${c.managed?'Setup Step 11 records working initial RHEL deployment but an incomplete Placement-driven integration. Windows managed recovery is a new task; neither flow is established by the closed discovered tasks.':'Setup records discovered recovery and Jira marks this task Closed. Historical CLI attempts, old namespace layouts and workarounds are not the current test procedure.'}</p><p>${jira('VIRTDR-274')}: historical source-array handle resolution. ${jira('VIRTDR-287')}: discovered Cleaning Up stall was reclassified as expected source-cleanup behavior. ${jira('VIRTDR-290')}: historical promoted-volume NVMe discovery issue. Status snapshot from the RHEL subtask: all three Closed.</p><p>UI issues tracked under the parent include ${['308','309','310','313','314','315','316','318'].map(n=>jira('VIRTDR-'+n)).join(', ')}. These are historical references, not a claim that the current UI reproduces every defect. Capture discrepancies against the current baseline.</p><p>The Dell investigation notes contain earlier appliance deployment/reboot experiments and tentative iSCSI descriptions. The Setup Doc's later PowerStore NVMe/TCP configuration governs these diagrams. Do not infer a Ramen defect from stale addresses or old array symptoms.</p></div>
    <h2>Run acceptance checklist</h2><p class="muted">Session-only reviewer checklist. Ticking boxes does not execute operations, persist run results or change Jira status.</p><div class="checklist">${checklist.map(t=>`<label><input type="checkbox">${esc(t)}</label>`).join('')}</div>
    <footer>Sources: ${jira('VIRTDR-218')} · ${jira('VIRTDR-'+id)} · <a href="${setup}">Setup Doc</a> · <a href="${notes}">Historical Dell notes</a> · <a href="${repo}/tree/ocp-4.22-rhdr-dell/clusters/dell-s4">Authoritative Dell workload branch</a> · <a href="https://github.com/RamenDR/ramen/blob/main/docs/usage.md">Ramen usage guide</a><p class="muted">Snapshot reviewed 2026-10-01. No live cluster check was performed to build this dashboard. Results require run-specific evidence; failback is outside this failover flow.</p></footer>`;

  const dia=document.getElementById('dia'), svg=document.getElementById('svg'), sizer=document.getElementById('sizer'), wrap=document.getElementById('wrap');
  let z=1, height=0;
  const width=stages.length*370-20;
  function scale(){dia.style.transform=`scale(${z})`;sizer.style.width=`${width*z}px`;sizer.style.height=`${height*z}px`;document.getElementById('zoom').textContent=Math.round(z*100)+'%';}
  function draw(){
    const cards=[...dia.querySelectorAll('.stage')];height=Math.max(...cards.map(el=>el.offsetTop+el.offsetHeight))+35;
    dia.style.minWidth=width+'px';dia.style.height=height+'px';svg.setAttribute('width',width);svg.setAttribute('height',height);
    svg.innerHTML=cards.slice(0,-1).map((a,i)=>{const b=cards[i+1],x1=a.offsetLeft+a.offsetWidth,x2=b.offsetLeft,y1=a.offsetTop+a.offsetHeight/2,y2=b.offsetTop+b.offsetHeight/2;return `<path d="M${x1} ${y1} C${x1+40} ${y1},${x2-40} ${y2},${x2} ${y2}" fill="none" stroke="#58a6ff" stroke-width="2"/><circle cx="${x1}" cy="${y1}" r="3" fill="#58a6ff"/><circle cx="${x2}" cy="${y2}" r="4" fill="#58a6ff"/>`;}).join('');scale();
  }
  document.getElementById('in').onclick=()=>{z=Math.min(1.5,z+.1);scale();};
  document.getElementById('out').onclick=()=>{z=Math.max(.2,z-.1);scale();};
  document.getElementById('fit').onclick=()=>{z=Math.min(1,wrap.clientWidth/width);scale();};
  document.getElementById('reset').onclick=()=>{z=1;scale();};
  window.addEventListener('resize',draw);document.fonts.ready.then(draw);
})();
