'use strict';
(() => {
  const id=document.body.dataset.flow, managed=['292','294'].includes(id), pending=id==='294';
  const ns=({291:'hammerdb',292:'gitops-vms',293:'hammerdb-win',294:'Not configured'})[id];
  const vm=id==='293'?'hammerdb-win':pending?'Not configured':'hammerdb-rhel9';
  const drpc=({291:'hammerdb-drpc',292:'dell-vm-drpc',293:'hammerdb-win-drpc',294:'Not configured'})[id];
  const placement=({291:'hammerdb-placement',292:'dell-vm-placement',293:'hammerdb-win-placement',294:'Not configured'})[id];
  const decision=pending?'Not configured':placement+'-decision-1';
  const bsl=pending?'Not configured':`openshift-dr-ops--${drpc}--0----minio-on-hub / openshift-dr-ops--${drpc}--1----minio-on-hub`;
  const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const why={
    ManagedCluster:'ACM needs an imported, reachable cluster identity to select a site and deliver work to it.',
    DRCluster:'Ramen needs each site’s DR configuration and validation before using it for recovery.',
    DRPolicy:'Provides the site pair and replication schedule shared by the protected applications.',
    DRPlacementControl:'Connects one application to its policy, placement and selected disks so recovery can be coordinated.',
    Placement:'Provides the named cluster-selection object that Ramen controls for this application.',
    PlacementDecision:'Publishes the selected site to consumers; preferredCluster alone does not tell them where to deploy.',
    ProtectedApplicationView:'Makes correlated protection/application information available to the console; it is not a storage or deployment controller.',
    ManifestWork:'Carries hub-generated desired resources to a spoke through ACM instead of requiring direct hub-side creation there.',
    VolumeReplicationGroup:'Coordinates the application’s protected PVCs, storage metadata and Primary/Secondary state as a unit.',
    ManagedClusterView:'Lets hub reconciliation observe remote resource state when this flow uses a view.',
    VolumeReplication:'Expresses the replication role of an individual protected disk for the csi-addons controller.',
    VolumeReplicationClass:'Supplies driver-specific replication settings; a matching schedule and provisioner are needed for class selection.',
    StorageClass:'Connects a disk request to the provisioner and its storage settings; each spoke needs the appropriate local configuration.',
    CSIDriver:'Registers the storage implementation and capabilities Kubernetes uses to work with the Dell driver.',
    'CSI + csi-addons':'Bridges Kubernetes storage/replication requests to Dell array operations and worker disk access.',
    'Array replica volumes':'Hold the recoverable database and OS blocks at the other site; Git and object backups cannot replace this data.',
    VirtualMachine:'Preserves guest hardware, boot and disk references so the recovered disks can run as the intended VM.',
    DataVolume:'Automates initial disk creation/population. During recovery, it must not overwrite a promoted disk with a fresh clone or blank disk.',
    PersistentVolumeClaim:'Gives the workload a namespaced disk reference and Ramen a selectable storage object.',
    PersistentVolume:'Records the backing CSI disk handle and binding needed to reconnect the correct recovered array volume.',
    VolumeAttachment:'Tracks the PV-to-worker CSI attachment required for a launcher to access its disk.',
    DataProtectionApplication:'Configures the Velero runtime/plugins used to protect and restore Kubernetes objects separately from block replication.',
    'Backup / Restore':'Capture and recreate workload configuration/dependencies; replicating VM disks alone does not recreate Kubernetes objects.',
    BackupStorageLocation:'Tells Velero where object archives are stored and how that location is referenced.',
    'MinIO / S3':'Retains DR metadata and object archives outside the protected workload site for recovery.',
    ApplicationSet:'In the managed flow, turns the selected cluster decision into a destination Application; a console marker alone is insufficient.',
    Application:'Tells Argo CD which revision/path to synchronize and to which cluster/namespace.',
    'ManagedClusterSet / Binding':'Makes the selected cluster set available to a namespaced Placement; cluster import alone does not establish that selection scope.',
    GitOpsCluster:'Connects ACM-selected clusters to Argo CD destination registration for the intended managed handoff.',
    ArgoCD:'Provides the running reconciliation controllers that apply generated Applications, with the required watch scope and permissions.',
    HyperConverged:'Configures the OpenShift Virtualization installation that supplies guest and disk-import capabilities.',
    'KubeVirt / CDI':'Provide the controllers implementing VM execution and DataVolume provisioning underneath virtualization.',
    VirtualMachineInstance:'Represents the executing guest whose readiness and disk access must be verified after recovery.',
    CatalogSource:'Makes operator bundles discoverable for OLM installation; it does not prove a particular installed version.',
    Subscription:'Requests an operator package/channel in the OLM install mechanism; this recorded RHDR snapshot does not establish an active Subscription.',
    InstallPlan:'Records the resolved OLM installation steps when that installation mechanism is used.',
    ClusterServiceVersion:'Describes the installed operator bundle, its APIs and controller deployment, distinct from a catalog update.',
    Recipe:'Can describe an object-protection workflow. Here its API was an operator dependency; an application-specific Recipe is not established.',
    VolumeGroupReplication:'Provides group replication when explicitly configured; two individually protected disks do not establish use of this API.',
    VolumeGroupReplicationClass:'Supplies settings for the conditional group-replication branch; the initial 5m class is not the selected 15m per-disk policy.',
    VolumeGroupSnapshotClass:'Configures a group-snapshot driver when that branch is used. Installed CRD presence does not establish a snapshot instance.'
  };
  // Explain the job first, then the handoff and the evidence a reader can inspect.
  const explain={
    ManagedCluster:['The hub’s address-book entry for a cluster it manages. Importing a spoke gives ACM a way to identify it and communicate with its agents.','Ramen uses the same spoke identity, but ACM availability and disaster-recovery readiness are separate checks. A reachable cluster can still have an unhealthy storage replica.','Check Joined and Available conditions for both spokes before trusting delivery or placement.'],
    DRCluster:['The disaster-recovery profile for one spoke, kept on the hub. It tells Ramen which site it is coordinating and which storage-metadata profile that site uses.','The two profiles let Ramen validate the recovery sites before moving an application. They do not contain the VM’s disks or replace the ACM cluster registration.','Inspect validation conditions and their reason/message; do not substitute a green ManagedCluster for DR validation.'],
    DRPolicy:['A shared recovery agreement: which two sites participate and how often asynchronous replication is scheduled. RPO means the allowed age of recoverable data.','The recorded dr-policy-15m pairs spoke-0 and spoke-1. Each application points to this policy; the selected per-disk replication class must support its schedule.','Check policy validation and the actual schedule. A 15-minute setting is a target, not proof that the latest array copy is less than 15 minutes old.'],
    DRPlacementControl:['The application’s recovery coordinator, often shortened to DRPC. Think of it as the instruction sheet that joins the application, eligible sites and recovery policy.','It references a Placement, identifies protected namespaces and selects disk claims by labels. Ramen reads this object on the hub and asks spoke controllers to protect or recover that particular workload.','Read phase, progression and conditions together. FailedOver with Cleaning Up is still intermediate; a completed phase alone does not prove that the guest database recovered.'],
    Placement:['A named cluster-selection request. It is the place where controllers agree which cluster should host an application.','For these DR placements, ordinary scheduling is disabled so Ramen can control the recovery decision. The separate registration Placement selects clusters for Argo CD access; it is not the application’s DR destination.','Follow the DRPC placementRef to the correct object, then read its PlacementDecision rather than guessing from a preferred-cluster field.'],
    PlacementDecision:['The published answer to a Placement: the selected cluster name. Consumers read this answer to find the intended destination.','In the managed design, an ApplicationSet consumes this decision and creates an Application for that cluster. Merely changing the answer does not prove that Argo CD has acted on it.','Compare the decision with the generated Application destination and actual VM/VMI location. Generated decision names are snapshot identities, not a naming contract.'],
    ProtectedApplicationView:['A console-facing summary that correlates a protected application with its disaster-recovery information. It helps the UI show the right application and status.','The orchestrator supplies this view on the hub. It observes and presents information; it does not copy disks, start a guest or deploy an application.','Compare its information with the DRPC and selected cluster if the console is empty or stale. Presence of a view is not proof that recovery succeeded.'],
    ManifestWork:['A delivery envelope sent from the hub to a managed cluster. Its payload contains Kubernetes resource definitions that the spoke’s ACM agent applies.','Here Ramen creates work in the hub namespace named for each spoke, and that work delivers the VolumeReplicationGroup to openshift-dr-ops on that spoke. Delivery is distinct from the later storage operation.','Inspect delivery and availability conditions, then the delivered VRG. Applied work proves the envelope arrived, not that the replica is healthy or the VM is running.'],
    VolumeReplicationGroup:['The spoke-side protection plan for one application, commonly called a VRG. It groups the selected disk claims and their recovery metadata under one recovery state.','The VRG lives in openshift-dr-ops, while its protected disk claims remain in the workload namespace. It coordinates per-disk replication and configured Kubernetes-object protection, and records Primary or Secondary state.','Check selected PVCs, per-PVC conditions, KubeObjectsReady and ClusterDataProtected. DataProtected=False with Replicating needs correlation with sync timestamps, not an automatic S3-failure diagnosis.'],
    ManagedClusterView:['A remote observation request: it lets a hub controller learn what a resource on a spoke currently looks like. Think of it as a status window, not a delivery envelope.','These views inspect the remote VRG after ManifestWork has delivered it. Ramen can then compare the requested state with the state reported by the spoke.','Inspect the view result and freshness, and compare with the spoke object when investigating a mismatch. The view does not own or create the observed VRG.'],
    VolumeReplication:['A replication instruction for one disk, not the whole VM. It refers to the disk’s PVC and asks for a Primary or Secondary role.','The VRG creates this resource for each selected claim. The csi-addons controller passes the requested role and selected class settings to the Dell driver, which operates on the array copy.','Verify each root and data disk separately: role, completed/degraded conditions, destination volume ID and actual array sync age. One healthy disk cannot stand in for both.'],
    VolumeReplicationClass:['A reusable recipe for replicating disks with a particular driver and schedule. It is a custom resource, despite having Class in its name.','The recorded powerstore-vrc-15m supplies Dell replication settings that match the 15-minute DRPolicy. Each spoke’s parameters describe its appropriate remote array direction.','Check the selected class and schedule. This class configures replication; StorageClass configures disk provisioning. Having one does not establish that the other is correct.'],
    StorageClass:['A menu entry for requesting storage, built into Kubernetes. A claim names this class so Kubernetes knows which driver and provisioning settings to use.','Both workload disks request powerstore-sc. Its provisioner is csi-powerstore.dellemc.com; the Dell CSI driver creates the array disk and Kubernetes binds a PV to the claim. The class is cluster-scoped, so each spoke has its own configuration.','Inspect provisioner, parameters, binding mode, reclaim policy and topology constraints on each spoke. This is not a custom resource or a replication schedule, and a fresh disk is not a recovered replica.'],
    CSIDriver:['Kubernetes’ built-in registration record for a storage driver. CSI stands for Container Storage Interface, the standard contract used to request and attach storage.','The name csi-powerstore.dellemc.com connects Kubernetes storage resources with the installed Dell implementation. The record describes driver capabilities; the actual controller and node pods do the work.','Check the registered driver and the readiness of controller/node pods. A registration object can exist while a driver pod or worker storage path is broken.'],
    'CSI + csi-addons':['The working controllers behind the storage objects. CSI handles creating, attaching and exposing disks; csi-addons adds the replication control path used here.','The Dell driver translates requests into PowerStore operations. Its node components make the correct array volume available to the worker over NVMe/TCP so the VM launcher can use it.','Check controller and node readiness, mount events, array sessions and visible namespaces. Two live network paths alone do not prove that the required disk is accessible.'],
    'Array replica volumes':['The actual copies of disk contents on the second PowerStore array. They contain the operating-system and database blocks needed for recovery.','Asynchronous replication copies changes from the source array to its partner. Recovery promotes the destination copy and reconnects Kubernetes to that copy rather than creating an empty replacement.','Compare replication-session IDs, source/destination disk handles, error state and last sync time. An unmapped replica can legitimately have no Kubernetes PV before promotion.'],
    VirtualMachine:['The saved definition of a virtual computer: CPU, memory, boot settings, network and disk references. It is configuration, not the running guest itself.','OpenShift Virtualization uses this definition to create a VirtualMachineInstance. Recovery needs both this definition and the correct promoted root/data disks; neither can replace the other.','Verify disk references, required namespace-local dependencies and boot configuration. A VM object can exist without a running or usable guest.'],
    DataVolume:['A disk-preparation request managed by CDI, the virtualization disk-import controller. It can populate a boot disk from an image or create a blank data disk during initial setup.','The RHEL reference clones the rhel9 DataSource for its root disk and starts with a blank database disk. The discovered Windows setup can clone its local golden-image PVC. These are bootstrap operations, not sources of recovered database data.','During recovery require reuse of promoted disks. On separately authorized source cleanup, remove the DataVolume before its owned PVC; otherwise its controller can try to recreate that claim.'],
    PersistentVolumeClaim:['The application’s request for a disk, usually shortened to PVC. It specifies capacity, access requirements and a StorageClass, and gives the VM a namespaced disk name to reference.','The rootdisk and datadisk claims are the objects Ramen selects for protection. A bound claim points to one PV; labels determine protection, so an unrelated or temporary CDI claim is not automatically included.','Bound means a claim is paired with a PV, not that the guest can read it. Inspect the selected labels, volumeName, events and actual recovered handle.'],
    PersistentVolume:['The cluster-wide record of a disk supplied to a claim, usually shortened to PV. It records capacity, the claim binding and the CSI volume handle for the real array disk.','The claim is the workload-facing name; the PV identifies the backing storage. On recovery the handle must resolve to the promoted destination copy, not the old source-array disk.','Compare the PV handle with VolumeReplication destination IDs and the array. Missing PV alone is not evidence that an unpromoted destination replica is an orphan.'],
    VolumeAttachment:['The cluster-wide record of a request to attach a PV to a particular worker. This connects a disk binding with the node where the workload runs.','The CSI attachment controller and node components carry out the request so the launcher pod can access its disks. It tracks attachment, not replication or the guest filesystem.','Inspect attachment status, errors and worker identity alongside mount events. A stale attachment for a deleted PV needs separate investigation and cleanup authorization.'],
    DataProtectionApplication:['OADP’s configuration for the Velero backup/restore service. It sets up the runtime and plugins used to save Kubernetes objects.','Disk replication preserves bytes, but the target also needs VM definitions and dependencies. Ramen’s configured object-protection path asks Velero to capture and restore those objects.','Check DPA and Velero readiness, then backup/archive evidence. A ready backup service alone does not prove this application’s backup completed.'],
    'Backup / Restore':['A Backup is a request and record of saving Kubernetes objects; a Restore asks Velero to recreate saved objects. These complement storage replication.','The archive must preserve required workload definitions and dependencies. Replicated database disks do not recreate a missing VM definition or its required Secret.','Require terminal backup success or verified archive read-back. No current Backup CR does not prove the stored archive is absent, and Finalizing alone does not prove success.'],
    BackupStorageLocation:['Velero’s address-book entry for an object archive destination. It identifies the S3 endpoint, bucket and credential references used by backup/restore jobs.','The per-application locations connect object protection to the hub MinIO service. They are configuration references, not the archive contents themselves.','Available means the location is usable according to its validation, not that a particular archive is complete. A missing target location alone does not establish archive loss.'],
    'MinIO / S3':['The object-storage service on the hub. S3 is its access protocol; it stores Ramen recovery metadata and Kubernetes-object archives separately from array disk copies.','This is the configuration and metadata recovery path. The database’s disk writes are copied by PowerStore replication, not by uploading every transaction to MinIO.','Correlate DR validation, VRG metadata/object-protection conditions and archive evidence. A reachable MinIO health endpoint is not proof that an application archive can be restored.'],
    ApplicationSet:['A template-driven factory for Argo CD Applications. In the intended managed flow it reads a cluster decision and generates the deployment instruction for that destination.','The RHEL reference uses the acm-placement ConfigMap to interpret PlacementDecision. The recorded namespace-scoping problem produced no generated Applications; an object used as a console type marker is not a working deployment factory.','Require generated Applications that actually follow the decision, suitable watch scope and registered destinations. Windows managed definitions remain unspecified.'],
    Application:['Argo CD’s deployment instruction: which Git repository, revision and folder to apply, and which cluster/namespace should receive them.','A generated Application is the handoff from placement to deployment. The authoritative Dell source is elsapassaro/ramendr-starter-kit, branch ocp-4.22-rhdr-dell; the RHEL workload folder is clusters/dell-s4/workloads.','Inspect destination, sync, health, operations and ownership. A healthy Application pinned to spoke-0 proves that deployment, not automatic recovery to spoke-1 or reuse of promoted disks.'],
    'ManagedClusterSet / Binding':['A cluster set groups managed clusters; its binding makes that group available to a Placement in a namespace. Import and selection permission are different concerns.','The recorded default bindings expose the appropriate cluster-selection scope in openshift-dr-ops and openshift-gitops. Registration and DR placements still have different jobs.','Check the referenced set and namespaced binding when selection is empty. A binding does not itself choose a recovery destination.'],
    GitOpsCluster:['The ACM-to-Argo CD registration bridge. It makes selected managed clusters available as Argo CD deployment destinations.','argo-acm-clusters uses the registration Placement all-openshift-clusters. This supplies destination registrations; the separate DR Placement decides where the protected workload should run.','Verify registration conditions and destination identity without reading Secret values. Registration alone does not generate or move the workload Application.'],
    ArgoCD:['The configuration of the running GitOps service. Its controllers compare desired Git definitions with tracked cluster resources and reconcile differences.','The openshift-gitops instance must have permission, namespace watch scope and destination registration for this managed path. Applications and ApplicationSets are instructions to those controllers, not substitutes for them.','Inspect instance/controller readiness and the actual generated Applications. Automatic prune/self-heal settings do not prove source cleanup or recovered-disk reuse.'],
    HyperConverged:['The main installation configuration for OpenShift Virtualization. Its operator coordinates the components needed to run guests and prepare their disks.','kubevirt-hyperconverged configures virtualization on each spoke. It supplies infrastructure for all the VM scenarios, not a per-application failover instruction.','Check component readiness and conditions. A healthy installation still needs a valid VM definition, accessible disks and a recovered guest.'],
    'KubeVirt / CDI':['The controllers underneath OpenShift Virtualization. KubeVirt runs virtual machines; CDI prepares and imports their disk contents.','The HyperConverged operator configures these components. KubeVirt is observed in openshift-cnv; the CDI configuration instance is cluster-scoped. Their scope must not be confused with the workload’s namespace.','Check controller readiness and workload events. Initial disk import success is distinct from correct use of a promoted disk during recovery.'],
    VirtualMachineInstance:['The actual execution of a VM, usually called a VMI. It records guest runtime state and the worker running the launcher pod.','The VM definition starts this instance. During recovery inspect the target VMI and its disks, then check services inside the guest to establish that the recovered database is usable.','Compare Running/readiness, launcher events and actual placement. Running alone does not prove database recovery, protection completion or data continuity.'],
    CatalogSource:['An operator-bundle catalog used by OLM, the Operator Lifecycle Manager. It makes installable operator versions discoverable.','The staging catalog provides RHDR bundles. Changing its image changes what is offered; it does not by itself install or upgrade the controllers already running.','Compare catalog readiness, channel head, installed CSV and actual controller image before claiming an upgrade.'],
    Subscription:['An OLM request to follow an operator package and channel. It controls how a catalog’s offered bundles are selected for installation.','OLM resolves this request through an InstallPlan. The recorded snapshot did not establish an active RHDR Subscription even though installed CSVs/controllers existed.','Inspect the real installation mechanism and requested/current version. Do not infer operator absence from Subscription absence alone.'],
    InstallPlan:['OLM’s resolved installation task list for an operator bundle and dependencies. It belongs to operator installation, not guest recovery.','A Subscription can lead to this plan, then installed APIs and a ClusterServiceVersion. Approval and completion states explain whether an offered update actually proceeded.','Read plan status alongside the installed CSV and running controller. A generated plan is not proof of a completed installation.'],
    ClusterServiceVersion:['The installed operator bundle description, commonly called a CSV. It describes the bundle’s APIs and controller deployment.','The recorded spoke RHDR CSV is distinct from hub operators and from a catalog image. The deployment/pod is the executing controller; the CSV is its installation record.','Check CSV phase, deployment readiness and image/version together. A version string alone does not prove healthy reconciliation.'],
    Recipe:['An optional custom workflow definition for Kubernetes-object capture and restore. It can describe which resources and steps belong in protection.','The Recipe API was an installation dependency here, but no application-specific Recipe instance was established in the recorded inventory. Ordinary object-protection evidence should not be replaced with an invented Recipe.','Distinguish an installed CRD from a configured instance and selected workflow. No Recipe instance is not automatically a failure for this path.'],
    VolumeGroupReplication:['An optional request to coordinate replication at a group level. It is a different API from the per-PVC VolumeReplication path shown above.','Two disks in one VM do not prove group replication is in use. The recorded group instance belongs to an unrelated busybox test, not these protected workloads.','Follow actual instance references before applying group assumptions. Verify root and data disk evidence through the active per-disk path.'],
    VolumeGroupReplicationClass:['Settings for the optional group-replication API. Like VolumeReplicationClass, it is a custom resource with cluster-wide scope.','powerstore-vgrc-5m belongs to the initial group-provider configuration. It is not the selected 15-minute per-disk policy used in these scenario references.','Check whether a workload group actually selects this class. Class existence alone does not establish a group-replication handoff.'],
    VolumeGroupSnapshotClass:['Settings for a driver capable of snapshots across a volume group. A snapshot is a point-in-time copy, distinct from the ongoing cross-array replication path.','The recorded inventory had the API definition but no class instances. This is a conditional capability, not evidence that these VMs use group snapshots.','Verify a configured class and the workload’s selected snapshot workflow before relying on it. An installed CRD alone does not supply either.'],
    DRClusterConfig:['The spoke controller’s cluster-specific configuration object. It gives that controller settings for its own DR site.','This complements the hub DRCluster: one configures the local controller, while the other represents the site to hub orchestration. The recorded instances are cluster-scoped.','Read the actual spoke instance and controller conditions rather than assuming the hub object proves local configuration.'],
    DataSource:['A named pointer to an image that CDI can use for initial disk population. It separates the boot-image reference from a changing underlying image PVC.','The RHEL rootdisk references rhel9 in openshift-virtualization-os-images. A new clone starts from that image, not from the protected VM’s most recent operating-system disk.','Check source readiness for bootstrap. During failover, verify the promoted rootdisk is used instead of a fresh image.'],
    Klusterlet:['The ACM agent configuration on an imported spoke. Its agents connect that cluster with the hub.','Those agents receive ManifestWork and report managed-cluster state. They are the delivery infrastructure under the DR controller chain, not a disk-replication implementation.','Check agent readiness and delivery feedback if hub work cannot reach a spoke.'],
    MultiClusterHub:['The ACM installation configuration on the hub. It provides the management services behind cluster import, application views and multi-cluster coordination.','The recorded instance is rhacm/multiclusterhub. It enables the platform used by DR workflows but does not select a particular application’s failover target.','Check relevant component readiness alongside the per-application objects; installation health is only one layer.'],
    MultiClusterEngine:['The cluster-lifecycle and registration infrastructure used with ACM. Its configuration object is cluster-scoped.','The operator runs in multicluster-engine. The object’s scope and the operator’s namespace are different concepts; neither is the namespace of a protected VM.','Verify lifecycle/registration components when cluster identity or availability is the problem, then inspect the DR-specific chain separately.'],
    MirrorPeer:['An ODF multi-cluster storage relationship used in a different recovery architecture. It is not the PowerStore array pairing in this lab.','This Dell path uses array-native replication controlled through csi-addons VolumeReplication. Copying an ODF MirrorPeer requirement into this flow would describe the wrong storage implementation.','Treat it as not applicable unless current workload evidence establishes an ODF dependency.'],
    Submariner:['A cross-cluster networking system used to connect cluster networks in architectures that require it. It does not mean all DR paths require a pod-network tunnel.','The recorded Dell disks replicate between arrays; this active path does not use the ODF/Submariner networking branch. Metadata and management traffic still need their configured connectivity.','Do not report missing Submariner as a Dell readiness failure without an actual configured dependency.'],
    DellCSIReplicationGroup:['A resource from the older Dell CSM replication integration. It belongs to a different control API than the active csi-addons implementation.','The current path uses VRG and per-disk VolumeReplication. This historical resource is shown to prevent confusion, not as an additional required controller step.','Follow the installed driver and selected API; do not troubleshoot the retired branch as though it controls this workload.']
  };
  const explanation=kind=>explain[kind].map((text,i)=>`<p><strong>${['In simple terms:','How it fits here:','What to check:'][i]}</strong> ${esc(pending&&i===1?'Shared infrastructure / reference behavior only; this Windows managed workload is not configured. '+text:text)}</p>`).join('');
  const palette={
    'openshift-dr-ops':'#bc8cff','openshift-gitops':'#ff8fb3',
    hammerdb:'#3fb950','gitops-vms':'#39d2c0','hammerdb-win':'#e3b341',
    'openshift-adp':'#58a6ff','openshift-cnv':'#f69d50',
    'openshift-marketplace':'#a5d6ff','openshift-dr-system':'#d2a8ff',
    powerstore:'#ffa657','csi-addons-system':'#ff7b72',minio:'#a5d675',
    'cluster-scoped':'#c9d1d9',external:'#8b949e',
    'not configured':'#9ba7b4','namespaced (no instances)':'#9ba7b4',test:'#9ba7b4','mixed scope':'#9ba7b4'
  };
  function namespaces(scope){
    const location=scope.split(' / ').slice(1).join(' / ');
    if(scope.startsWith('External')) return ['external'];
    if(location==='cluster-scoped') return ['cluster-scoped'];
    if(location.includes('cluster-scoped;')) return ['mixed scope'];
    const keys=location.split(' + ');
    return keys.every(key=>Object.hasOwn(palette,key))?keys:['mixed scope'];
  }
  palette['spoke-0']='#79c0ff';palette['spoke-1']='#f778ba';
  const n=(kind,name,scope,detail,type='cr')=>({kind,name,scope,detail,type});
  const hub='Hub / openshift-dr-ops', spoke=pending?'Spokes / not configured':`Spoke-0 (current); spoke-1 (recovery) / ${ns}`;
  const d=n('DRPlacementControl',drpc,hub,'References DRPolicy, Placement, protectedNamespaces and PVC selector.');
  const v=n('VolumeReplicationGroup',drpc,'Each spoke / openshift-dr-ops','Live inventory: VRG name matches DRPC, in openshift-dr-ops on both spokes. Protected PVCs remain in the workload namespace. Windows managed VRG is not configured.');
  const m=n('VirtualMachine',vm,spoke,'VM configuration references root/data disks; starts a VirtualMachineInstance and launcher Pod.');
  const lanes=[
    ['Policy and DR site eligibility',[
      n('ManagedCluster','spoke-0 / spoke-1','Hub / cluster-scoped','ACM import/availability is distinct from DR validation.'),
      n('DRCluster','spoke-0 / spoke-1','Hub / cluster-scoped','Ramen site identity, validation and S3 profile.'),
      n('DRPolicy','dr-policy-15m','Hub / cluster-scoped','Pairs DRClusters; recorded schedule 15m.'),d
    ],['same site identity','drClusters[]','drPolicyRef']],
    ['DR placement and console observation',[
      d,n('Placement',placement,hub,'DRPC placementRef; DR controls the decision instead of ordinary scheduling.'),
      n('PlacementDecision',decision,hub,'Observed controller-generated instance; status.decisions selects the active spoke. Names are a snapshot, not a universal naming guarantee.'),
      n('ProtectedApplicationView',drpc,hub,'Live hub inventory verifies this per-DRPC view in openshift-dr-ops. Orchestrator correlates DRPC/application state for the UI. Observation, not deployment; Windows managed view is not configured.')
    ],['placementRef','decision status','UI correlates decision + DRPC']],
    ['Cross-cluster delivery and status',[
      d,n('ManifestWork',pending?'Not configured':drpc+'-openshift-dr-ops-vrg-mw','Hub / spoke-0 + spoke-1','One observed instance in each hub spoke namespace. ACM agent delivers the VRG to openshift-dr-ops on that spoke.'),v,
      n('ManagedClusterView',pending?'Not configured':drpc+'-openshift-dr-ops-vrg-mcv','Hub / spoke-0 + spoke-1','One observed instance in each hub spoke namespace. Observes remote VRG status; does not own the VRG.')
    ],['Ramen reconciles','delivers VRG','observes status']],
    ['Protected disk replication',[
      v,n('VolumeReplication','One per selected PVC',spoke,'dataSource references PVC; desired role drives Dell replication.'),
      n('VolumeReplicationClass','powerstore-vrc-15m','Spokes / cluster-scoped','Matched by CSI provisioner and schedule; mirrored A-to-B / B-to-A parameters.'),
      n('CSI + csi-addons','Dell controllers','Spokes / powerstore + csi-addons-system','Translate replication requests into PowerStore API operations.','external'),
      n('Array replica volumes','VSA-A / VSA-B','External / no namespace','Array-native block replication, separate from S3 and Git.','external')
    ],['creates for PVC','class reference','controller interprets','array API']],
    ['Storage provisioning: claims, class and driver',[
      n('PersistentVolumeClaim',pending?'Not configured':`${vm}-rootdisk / ${vm}-datadisk`,spoke,pending?'Windows managed claims and their storage choice are not configured. The RHEL reference uses powerstore-sc; that does not establish Windows managed definitions.':'Both disks request storageClassName: powerstore-sc; the RHEL upstream DataVolume definitions verify that provisioning choice.','builtin'),
      n('StorageClass','powerstore-sc','Spokes / cluster-scoped','Recorded workload provisioning class; distinct from powerstore-vrc-15m replication settings.','builtin'),
      n('CSIDriver','csi-powerstore.dellemc.com','Spokes / cluster-scoped','Kubernetes driver registration for Dell PowerStore storage.','builtin'),
      n('CSI + csi-addons','Dell controllers','Spokes / powerstore + csi-addons-system','Controller/node implementation behind provisioning, attachment and replication.','external')
    ],['storageClassName','provisioner identity','driver implementation']],
    ['VM disk provisioning and binding',[
      m,n('DataVolume',pending?'Not configured':`${vm}-rootdisk / ${vm}-datadisk`,spoke,'CDI provisions initial disks and owns corresponding PVCs. Recovery must reuse promoted disks.'),
      n('PersistentVolumeClaim',pending?'Not configured':`${vm}-rootdisk / ${vm}-datadisk`,spoke,'VRG selects protected disks; excludes unlabeled CDI temporary claims.','builtin'),
      n('PersistentVolume','Dynamic / restored name','Spokes / cluster-scoped','PVC binding; CSI volume handle identifies the actual array disk.','builtin'),
      n('VolumeAttachment','Generated attachment','Spokes / cluster-scoped','References PV + worker; CSI publishes disk to the VM launcher.','builtin')
    ],['references disk','owns initial PVC','volumeName binding','PV + worker']],
    ['Kubernetes object protection (not block data)',[
      v,n('DataProtectionApplication','velero','Spokes / openshift-adp','Observed on both spokes. Runs Velero/plugins; Ramen requests capture/restore via kubeObjectProtection.'),
      n('Backup / Restore','No current CR instances','Spokes / openshift-adp','Read-only inventory returned no Backup or Restore CRs. Run-generated names are transient; absence of a CR does not establish absence of a stored S3 archive.'),
      n('BackupStorageLocation',bsl,'Spokes / openshift-adp',pending?'Windows managed location is not configured.':`Observed locations for slots 0 and 1. ${id==='292'?'Present on spoke-0; no dell-vm-drpc location on spoke-1 in this snapshot. This alone does not establish a recovery failure.':'Present on both spokes.'} S3 endpoint/credential references, not proof of archive completion.`),
      n('MinIO / S3','ramen-metadata','Hub / minio','Metadata and object archives; not VM disk writes.','external')
    ],['requests via Velero','executes backup / restore','storageLocation','S3 archive']]
  ];
  if(managed) lanes.push(
    ['GitOps workload handoff (intended; acceptance must be demonstrated)',[
      n('PlacementDecision',decision,hub,'Selects a registered destination cluster.'),
      n('ApplicationSet',pending?'Not configured':'dell-vm-workload',hub,'Observed RHEL instance: Degraded, no clusterDecisionResources found. Generator uses acm-placement; existence is not a functioning handoff.'),
      n('Application',pending?'Not configured':'No current instances; template dell-vm-workload-{{name}}',hub,'No Application instances returned by live hub inventory. Template source: upstream ocp-4.22-rhdr-dell, clusters/dell-s4/workloads (RHEL reference). Template is not an observed deployment.'),m
    ],['generator reads','generates','Argo CD syncs']],
    ['GitOps registration (separate from DR Placement)',[
      n('ManagedClusterSet / Binding','default / default','Hub / cluster-scoped; openshift-gitops + openshift-dr-ops','Observed default ManagedClusterSet and default bindings in openshift-gitops and openshift-dr-ops. Registration Placement remains separate from DR Placement.'),
      n('Placement','all-openshift-clusters','Hub / openshift-gitops','Registration selection, not the DR workload decision.'),
      n('GitOpsCluster','argo-acm-clusters','Hub / openshift-gitops','Uses registration Placement and supplies Argo CD cluster-registration Secrets.'),
      n('ArgoCD','openshift-gitops','Hub / openshift-gitops','Observed instance in openshift-gitops. Requires registered destinations, watch scope and RBAC to reconcile Applications.')
    ],['exposes clusters','placementRef','registers for']]
  );
  lanes.push(
    ['Virtualization installation and execution',[
      n('HyperConverged','kubevirt-hyperconverged','Spokes / openshift-cnv','Installation CR enables virtualization.'),
      n('KubeVirt / CDI','kubevirt-kubevirt-hyperconverged / cdi-kubevirt-hyperconverged','Spokes / openshift-cnv + cluster-scoped','Observed KubeVirt in openshift-cnv and cluster-scoped CDI on both spokes. HCO reconciles virtualization and disk import controllers.'),m,
      n('VirtualMachineInstance',vm,spoke,'Running guest instance; launcher Pod attaches the selected disks.')
    ],['reconciles','controllers implement','starts instance']],
    ['Operator installation (recorded mechanism, not an active upgrade)',[
      n('CatalogSource','rhdr-staging-catalog','All clusters / openshift-marketplace','Supplies RHDR bundles; catalog readiness does not prove an upgrade.'),
      n('Subscription','No active RHDR instance in recorded snapshot','RHDR spokes / openshift-dr-system','Historical installation mechanism; absence of a Subscription does not mean the installed CSV/controller is absent.'),
      n('InstallPlan','Run-generated installation record','RHDR spokes / openshift-dr-system','Historical OLM installation dependency; not an active workload-recovery resource.'),
      n('ClusterServiceVersion','rhdr-cluster-operator.v4.22.0-86.stable','RHDR spokes / openshift-dr-system','Observed spoke CSV. Hub hub/multicluster CSVs are separate from this spoke controller.')
    ],['bundle catalog','resolves bundle','installs CSV']],
    ['Conditional API dependencies (not established workload instances)',[
      n('Recipe','No current instances','Spokes / namespaced (no instances)','Namespaced CRD present, but no Recipe instances returned on either spoke. No active Recipe namespace to label.'),
      n('VolumeGroupReplication','No selected-workload instances','Unrelated spoke-0 example / test','Only observed instance is vgr-4251c970ec7af885d6ec79c1d2c40661-busybox in spoke-0/test, unrelated to these workloads. No instance on spoke-1.'),
      n('VolumeGroupReplicationClass','powerstore-vgrc-5m (initial setup)','Spokes / cluster-scoped','Class for the optional group replication branch.'),
      n('VolumeGroupSnapshotClass','No current instances','Spokes / cluster-scoped','CRD installed; no configured class instances returned on either spoke. Separate, conditional snapshot branch.')
    ],[null,'class if group API used',null]]
  );
  const section=document.createElement('section');section.id='resource-dependencies';
  const used=[...new Set(lanes.flatMap(([,nodes])=>nodes.flatMap(a=>namespaces(a.scope))))];
  const badges=a=>namespaces(a.scope).map(key=>`<span class="namespace-badge" style="--ns-color:${palette[key]}">${esc(key)}</span>`).join('');
  section.innerHTML=`<h2>CRD dependency diagram and namespaces</h2><p>A CustomResourceDefinition (CRD) itself is always cluster-scoped. The custom resources it defines can be namespaced or cluster-scoped, according to the CRD's <code>spec.scope</code>. These cards show <b>custom-resource instances</b> and their cluster/namespace, plus the built-in resources and services they depend on. Card stripes and badges identify namespace/scope; resource type is labeled separately. Connections describe references, reconciliation or observation, not universal ownership. Open <b>Use and why needed</b> on any card for an explanation (click, tap or keyboard).</p>
    <div class="notice"><b>Resource identity snapshot: 2026-10-04, read-only inventory of hub edge36 and spokes edge95/edge97.</b> Concrete names/scopes below were observed; recovery connections remain intended handoffs, not a completed test or continuous monitoring. Repeated cards represent the same object. VM/VMI instances for all three configured workloads were on spoke-0, with none on spoke-1. ${pending?'Windows managed workload resources are not configured; shared infrastructure is verified, but it is not an observed Windows managed deployment.':`Protected namespace: <b>${ns}</b>. Hub DRPC/PAV and both spoke VRGs: <b>openshift-dr-ops/${drpc}</b>.`} ${managed?'The historical fixed-spoke bootstrap is not proof of Placement-driven handoff; no Applications were returned in the current inventory.':'GitOps workload reconciliation is N/A here; ArgoCD APIs remain an orchestrator installation prerequisite.'}</div>
    <div class="namespace-legend" aria-label="Namespace color legend">${used.map(key=>`<span class="namespace-badge" style="--ns-color:${palette[key]}">${esc(key)}</span>`).join('')}</div>
    <div class="toolbar"><button id="resource-fit">Fit dependencies</button><button id="resource-reset">100%</button><button id="resource-expand">Expand explanations</button><button id="resource-collapse">Collapse explanations</button><span class="muted">Scroll horizontally at full scale. Each row traces a labeled dependency path.</span></div>
    <div class="wrap" id="resource-wrap"><div class="sizer" id="resource-sizer"><div id="resource-dia"><svg id="resource-svg" aria-hidden="true"></svg>${lanes.map(([title,nodes],row)=>`<div class="resource-lane-title" data-row="${row}">${esc(title)}</div>${nodes.map((a,col)=>`<article class="resource-node" data-row="${row}" data-col="${col}" data-type="${a.type}" style="--ns-color:${namespaces(a.scope).length===1?palette[namespaces(a.scope)[0]]:palette['mixed scope']}"><small>${esc(a.scope)}</small><div class="namespace-badges">${badges(a)}</div><small class="resource-type">${a.type==='cr'?'Custom resource':a.type==='builtin'?'Built-in resource':'Controller / external service'}</small><h3>${esc(a.kind)}</h3><b>${esc(a.name)}</b><details><summary>Use and why needed<span class="sr-only">: ${esc(a.kind)}</span></summary><p><strong>Used for:</strong> ${esc(a.detail)}</p><p><strong>Why needed:</strong> ${esc(why[a.kind])}</p></details></article>`).join('')}`).join('')}</div></div></div>
    <h3>Supporting configuration and conditional custom resources</h3><div class="table-wrap"><table><thead><tr><th>Kind / resource</th><th>Cluster / namespace or scope</th><th>Relationship and applicability</th></tr></thead><tbody>
    <tr><td>DRClusterConfig</td><td>Cluster-scoped: spoke-0 on edge95; spoke-1 on edge97</td><td>Observed cluster controller configuration instances.</td></tr>
    <tr><td>HyperConverged; KubeVirt; CDI</td><td>Each spoke: openshift-cnv/kubevirt-hyperconverged; openshift-cnv/kubevirt-kubevirt-hyperconverged; cluster-scoped cdi-kubevirt-hyperconverged</td><td>Observed virtualization and disk-import configuration instances. CDI is cluster-scoped, not in openshift-cnv.</td></tr>
    <tr><td>DataSource</td><td>RHEL: openshift-virtualization-os-images/rhel9</td><td>Initial RHEL rootdisk sourceRef. Windows discovered uses golden PVC windows-golden-images/windows-server-2022-standard (built-in). Fresh cloning is not recovery.</td></tr>
    <tr><td>StorageClass; CSIDriver</td><td>Spokes / cluster-scoped (built-in)</td><td>Shown as expandable cards in the storage-provisioning row above. PVC storageClassName powerstore-sc selects provisioner csi-powerstore.dellemc.com; the PV holds the actual disk handle. StorageClass provisions storage; VolumeReplicationClass configures replication.</td></tr>
    <tr><td>Recipe; VolumeGroupReplication; VolumeGroupReplicationClass; VolumeGroupSnapshotClass</td><td>Spokes / Recipe and group replication namespaced; classes cluster-scoped</td><td>No Recipe or VolumeGroupSnapshotClass instances observed. Group replication exists only in unrelated spoke-0/test. powerstore-vgrc-5m is initial provider setup, not evidence these workloads use group replication.</td></tr>
    <tr><td>CatalogSource; Subscription; InstallPlan; ClusterServiceVersion</td><td>Catalog: openshift-marketplace; spoke RHDR CSV: openshift-dr-system; hub GitOps/RHDR controllers: openshift-operators</td><td>OLM installation path, distinct from workload recovery. Recorded absence of active RHDR Subscriptions does not remove installed CSV/controller instances.</td></tr>
    <tr><td>ManagedClusterSet / Binding; Klusterlet; MultiClusterHub / MultiClusterEngine</td><td>Hub default/global sets: cluster-scoped; default bindings: openshift-dr-ops and openshift-gitops; spoke Klusterlet: cluster-scoped klusterlet; hub MCH: rhacm/multiclusterhub; MCE: cluster-scoped multiclusterengine</td><td>Observed identities for cluster selection, agent delivery and management installation. MCE operator namespace is multicluster-engine; its CR is cluster-scoped.</td></tr>
    <tr><td>Secret; ConfigMap; Service; Route; Deployment; Pod</td><td>Built-in, namespace of consuming controller or workload</td><td>Ramen S3 profiles/CA and ramen-s3-secret; RHEL cloudinit-hammerdb in VM namespace; managed acm-placement in openshift-dr-ops and cluster-registration Secrets in openshift-gitops; CSI array configuration and MinIO routing. No credential values shown.</td></tr>
    <tr><td>MirrorPeer; Submariner; DellCSIReplicationGroup</td><td>Not in this active Dell recovery path</td><td>ODF networking/replication and retired Dell CSM configuration must not be confused with csi-addons VolumeReplication.</td></tr>
    </tbody></table></div><p><b>How to trace a failure:</b> DRPC reference/validation, PlacementDecision, ManifestWork delivery, VRG/PVC selection, per-disk replication, target PV/attachment, object restore or GitOps destination reconciliation, then VM/VMI and guest. Follow actual owner references to distinguish ownership from a selector or status view.</p>
    <p>Sources: <a href="https://docs.google.com/document/d/1npumTvaf2SRj2wdEUoBBuYLZXwqXxJNUvY3SNqrLfe0/edit">Setup Doc, installation/transition and Step 11</a> · <a href="https://github.com/elsapassaro/ramendr-starter-kit/tree/ocp-4.22-rhdr-dell/clusters/dell-s4/hub-dr">Verified upstream DRPC / Placement / ApplicationSet</a>. Read live references before treating recorded names as current state.</p>`;
  const anchor=[...document.querySelectorAll('h2')].find(el=>el.textContent==='Pre-failover readiness gates');anchor.before(section);
  const supporting={
    DRClusterConfig:['Spoke-side DR cluster configuration: spoke-0 and spoke-1.','Provides cluster-specific settings used by the Ramen cluster controller; both instances are cluster-scoped.'],
    DataSource:['CDI reference to an image source such as rhel9.','Decouples initial rootdisk population from the underlying image PVC. It is not the failover disk source.'],
    Klusterlet:['ACM agent configuration on an imported spoke.','Enables the agents that receive hub work and report managed-cluster state.'],
    MultiClusterHub:['ACM installation configuration: rhacm/multiclusterhub.','Provides hub management services behind cluster import, selection and observation; not a per-workload failover trigger.'],
    MultiClusterEngine:['MCE installation configuration: cluster-scoped multiclusterengine.','Provides cluster lifecycle/registration infrastructure; operator runs in multicluster-engine.'],
    MirrorPeer:['ODF multicluster storage relationship.','Not needed by this Dell array-native path; shown only to distinguish the ODF architecture.'],
    Submariner:['Cross-cluster networking configuration.','Not part of the current Dell path; array replication does not use an ODF pod-network tunnel.'],
    DellCSIReplicationGroup:['Resource from the retired Dell CSM replication path.','Not needed by the active Ramen/csi-addons VolumeReplication workflow.']
  };
  const support=document.createElement('div');support.className='support-explanations';
  support.innerHTML='<h3>Other custom resources: use and why needed</h3>'+Object.entries(supporting).map(([kind,[use,reason]])=>`<details><summary>${esc(kind)}</summary>${explanation(kind)}<p><strong>Recorded configuration:</strong> ${esc(use)}</p><p><strong>Why needed / applicability:</strong> ${esc(reason)}</p></details>`).join('');
  section.querySelector('.table-wrap').after(support);
  const dia=document.getElementById('resource-dia'),svg=document.getElementById('resource-svg'),sizer=document.getElementById('resource-sizer'),wrap=document.getElementById('resource-wrap');
  dia.querySelectorAll('.resource-node').forEach(card=>card.querySelector('summary').insertAdjacentHTML('afterend',explanation(card.querySelector('h3').textContent)));
  const width=2180;let zoom=1,height=0;
  function scale(){dia.style.transform=`scale(${zoom})`;sizer.style.width=width*zoom+'px';sizer.style.height=height*zoom+'px';}
  function draw(){
    let top=20;const edges=[];
    lanes.forEach(([,nodes,links],row)=>{
      dia.querySelector(`.resource-lane-title[data-row="${row}"]`).style.top=top+'px';top+=38;
      const cards=[...dia.querySelectorAll(`.resource-node[data-row="${row}"]`)];
       cards.forEach((el,col)=>{el.style.left=20+col*435+'px';el.style.top=top+'px';});
      cards.slice(0,-1).forEach((a,col)=>{
        if(!links[col]) return;
        const b=cards[col+1],x1=a.offsetLeft+a.offsetWidth,x2=b.offsetLeft,y=top+Math.min(a.offsetHeight,b.offsetHeight)/2;
        const lines=[];let line='';links[col].split(' ').forEach(word=>{if((line+' '+word).trim().length>15){if(line)lines.push(line);line=word;}else line=(line+' '+word).trim();});if(line)lines.push(line);
        edges.push(`<path d="M${x1} ${y} C${x1+35} ${y},${x2-35} ${y},${x2} ${y}" fill="none" stroke="#58a6ff" stroke-width="2"/><circle cx="${x1}" cy="${y}" r="3" fill="#58a6ff"/><circle cx="${x2}" cy="${y}" r="4" fill="#58a6ff"/><text x="${(x1+x2)/2}" y="${y+22}" text-anchor="middle" fill="#c9d1d9" font-size="11">${lines.map((l,i)=>`<tspan x="${(x1+x2)/2}" dy="${i?14:0}">${esc(l)}</tspan>`).join('')}</text>`);
      });top+=Math.max(...cards.map(el=>el.offsetHeight))+35;
    });height=top;dia.style.width=width+'px';dia.style.height=height+'px';svg.setAttribute('width',width);svg.setAttribute('height',height);svg.innerHTML=edges.join('');scale();
  }
  document.getElementById('resource-fit').onclick=()=>{zoom=Math.min(1,wrap.clientWidth/width);scale();};
  document.getElementById('resource-reset').onclick=()=>{zoom=1;scale();};
  dia.addEventListener('toggle',draw,true);
  document.getElementById('resource-expand').onclick=()=>{section.querySelectorAll('details').forEach(el=>{el.open=true;});draw();};
  document.getElementById('resource-collapse').onclick=()=>{section.querySelectorAll('details').forEach(el=>{el.open=false;});draw();};
  window.addEventListener('resize',draw);document.fonts.ready.then(draw);
})();
